services:
  app-alpine:
    image: flask-app:alpine
    ports:
      - "8001:8000"
    mem_limit: 256m
    depends_on:
      - db

  app-alpine-multi:
    image: flask-app:alpine-multi
    ports:
      - "8002:8000"
    mem_limit: 256m
    depends_on:
      - db

  app-alpine-multi-bytecode:
    image: flask-app:alpine-multi
    ports:
      - "8003:8000"
    mem_limit: 256m
    depends_on:
      - db

  app-slim:
    image: flask-app:slim
    ports:
      - "8004:8000"
    mem_limit: 256m
    depends_on:
      - db

  app-slim-multi:
    image: flask-app:slim-multi
    ports:
      - "8005:8000"
    mem_limit: 256m
    depends_on:
      - db

  app-slim-multi-bytecode:
    image: flask-app:slim-multi-bytecode
    ports:
      - "8006:8000"
    mem_limit: 256m
    depends_on:
      - db

  app-full:
    image: flask-app:full
    ports:
      - "8007:8000"
    mem_limit: 256m
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flaskdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
